### ISSUE TITLE
Error loading state_dict for OptimizedModule: Missing key(s) in state_dict

### ISSUE THREAD

**Issue by severinbro** [justchenhao/SILI_CD#2]
When following the steps for a Quick Start:

- Download the checkpoint at https://pan.baidu.com/s/1R2XWu4lDfU1emhXbgrx17A (code: 358c) , and put the folder ours_levir1x in the folder checkpoints;
- Execute the script python try_cd.py to evaluate our model;
- The prediction results for samples in samples/levir_cut are saved in the folder checkpoints/ours_levir1x. Here, you can see the prediction results of different bitemporal resolution difference ratios.

This error arises:

File ~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2152, in Module.load_state_dict(self, state_dict, strict, assign)
   2147         error_msgs.insert(
   2148             0, 'Missing key(s) in state_dict: {}. '.format(
   2149                 ', '.join(f'"{k}"' for k in missing_keys)))
   2151 if len(error_msgs) > 0:
-> 2152     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2153                        self.__class__.__name__, "\n\t".join(error_msgs)))
   2154 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for OptimizedModule:
	Missing key(s) in state_dict: "_orig_mod.backbone.backbone.conv1.weight", "_orig_mod.backbone.backbone.bn1.weight", "_orig_mod.backbone.backbone.bn1.bias", "_orig_mod.backbone.backbone.bn1.running_mean", "_orig_mod.backbone.backbone.bn1.running_var", "_orig_mod.backbone.backbone.layer1.0.conv1.weight", "_orig_mod.backbone.backbone.layer1.0.bn1.weight", "_orig_mod.backbone.backbone.layer1.0.bn1.bias", "_orig_mod.backbone.backbone.layer1.0.bn1.running_mean", "_orig_mod.backbone.backbone.layer1.0.bn1.running_var", "_orig_mod.backbone.backbone.layer1.0.conv2.weight", "_orig_mod.backbone.backbone.layer1.0.bn2.weight", "_orig_mod.backbone.backbone.layer1.0.bn2.bias", "_orig_mod.backbone.backbone.layer1.0.bn2.running_mean", "_orig_mod.backbone.backbone.layer1.0.bn2.running_var", "_orig_mod.backbone.backbone.layer1.1.conv1.weight", "_orig_mod.backbone.backbone.layer1.1.bn1.weight", "_orig_mod.backbone.backbone.layer1.1.bn1.bias", "_orig_mod.backbone.backbone.layer1.1.bn1.running_mean", "_orig_mod.backbone.backbone.layer1.1.bn1.running_var", "_orig_mod.backbone.backbone.layer1.1.conv2.weight", "_orig_mod.backbone.backbone.layer1.1.bn2.weight", "_orig_mod.backbone.backbone.layer1.1.bn2.bias", "_orig_mod.backbone.backbone.layer1.1.bn2.running_mean", "_orig_mod.backbone.backbone.layer1.1.bn2.running_var", "_orig_mod.backbone.backbone.layer2.0.conv1.weight", "_orig_mod.backbone.backbone.layer2.0.bn1.weight", "_orig_mod.backbone.backbone.layer2.0.bn1.bias", "_orig_mod.backbone.backbone.layer2.0.bn1.running_mean", "_orig_mod.backbone.backbone.layer2.0.bn1.running_var", "_orig_mod.backbone.backbone.layer2.0.conv2.weight", "_orig_mod.backbone.backbone.layer2.0.bn2.weight", "_orig_mod.backbone.backbone.layer2.0.bn2.bias", "_orig_mod.backbone.backbone.layer2.0.bn2.running_mean", "_orig_mod.backbone.backbone.layer2.0.bn2.running_var", "_orig_mod.backbone.backbone.layer2.0.downsample.0.weight", "_orig_mod.backbone.backbone.layer2.0.downsample.1.weight", "_orig_mod.backbone.backbone.layer2.0.downsample.1.bias", "_orig_mod.backbone.backbone.layer2.0.downsample.1.running_mean", "_orig_mod.backbone.backbone.layer2.0.downsample.1.running_var", "_orig_mod.backbone.backbone.layer2.1.conv1.weight", "_orig_mod.backbone.backbone.layer2.1.bn1.weight", "_orig_mod.backbone.backbone.layer2.1.bn1.bias", "_orig_mod.backbone.backbone.layer2.1.bn1.running_mean", "_orig_mod.backbone.backbone.layer2.1.bn1.running_var", "_orig_mod.backbone.backbone.layer2.1.conv2.weight", "_orig_mod.backbone.backbone.layer2.1.bn2.weight", "_orig_mod.backbone.backbone.layer2.1.bn2.bias", "_orig_mod.backbone.backbone.layer2.1.bn2.running_mean", "_orig_mod.backbone.backbone.layer2.1.bn2.running_var", "_orig_mod.backbone.backbone.layer3.0.conv1.weight", "_orig_mod.backbone.backbone.layer3.0.bn1.weight", "_orig_mod.backbone.backbone.layer3.0.bn1.bias", "_orig_mod.backbone.backbone.layer3.0.bn1.running_mean", "_orig_mod.backbone.backbone.layer3.0.bn1.running_var", "_orig_mod.backbone.backbone.layer3.0.conv2.weight", "_orig_mod.backbone.backbone.layer3.0.bn2.weight", "_orig_mod.backbone.backbone.layer3.0.bn2.bias", "_orig_mod.backbone.backbone.layer3.0.bn2.running_mean", "_orig_mod.backbone.backbone.layer3.0.bn2.running_var", "_orig_mod.backbone.backbone.layer3.0.downsample.0.weight", "_orig_mod.backbone.backbone.layer3.0.downsample.1.weight", "_orig_mod.backbone.backbone.layer3.0.downsample.1.bias", "_orig_mod.backbone.backbone.layer3.0.downsample.1.running_mean", "_orig_mod.backbone.backbone.layer3.0.downsample.1.running_var", "_orig_mod.backbone.backbone.layer3.1.conv1.weight", "_orig_mod.backbone.backbone.layer3.1.bn1.weight", "_orig_mod.backbone.backbone.layer3.1.bn1.bias", "_orig_mod.backbone.backbone.layer3.1.bn1.running_mean", "_orig_mod.backbone.backbone.layer3.1.bn1.running_var", "_orig_mod.backbone.backbone.layer3.1.conv2.weight", "_orig_mod.backbone.backbone.layer3.1.bn2.weight", "_orig_mod.backbone.backbone.layer3.1.bn2.bias", "_orig_mod.backbone.backbone.layer3.1.bn2.running_mean", "_orig_mod.backbone.backbone.layer3.1.bn2.running_var", "_orig_mod.backbone.backbone.layer4.0.conv1.weight", "_orig_mod.backbone.backbone.layer4.0.bn1.weight", "_orig_mod.backbone.backbone.layer4.0.bn1.bias", "_orig_mod.backbone.backbone.layer4.0.bn1.running_mean", "_orig_mod.backbone.backbone.layer4.0.bn1.running_var", "_orig_mod.backbone.backbone.layer4.0.conv2.weight", "_orig_mod.backbone.backbone.layer4.0.bn2.weight", "_orig_mod.backbone.backbone.layer4.0.bn2.bias", "_orig_mod.backbone.backbone.layer4.0.bn2.running_mean", "_orig_mod.backbone.backbone.layer4.0.bn2.running_var", "_orig_mod.backbone.backbone.layer4.0.downsample.0.weight", "_orig_mod.backbone.backbone.layer4.0.downsample.1.weight", "_orig_mod.backbone.backbone.layer4.0.downsample.1.bias", "_orig_mod.backbone.backbone.layer4.0.downsample.1.running_mean", "_orig_mod.backbone.backbone.layer4.0.downsample.1.running_var", "_orig_mod.backbone.backbone.layer4.1.conv1.weight", "_orig_mod.backbone.backbone.layer4.1.bn1.weight", "_orig_mod.backbone.backbone.layer4.1.bn1.bias", "_orig_mod.backbone.backbone.layer4.1.bn1.running_mean", "_orig_mod.backbone.backbone.layer4.1.bn1.running_var", "_orig_mod.backbone.backbone.layer4.1.conv2.weight", "_orig_mod.backbone.backbone.layer4.1.bn2.weight", "_orig_mod.backbone.backbone.layer4.1.bn2.bias", "_orig_mod.backbone.backbone.layer4.1.bn2.running_mean", "_orig_mod.backbone.backbone.layer4.1.bn2.running_var", "_orig_mod.backbone.backbone.fc.weight", "_orig_mod.backbone.backbone.fc.bias", "_orig_mod.backbone.bi_inter_models.0.norm1.weight", "_orig_mod.backbone.bi_inter_models.0.norm1.bias", "_orig_mod.backbone.bi_inter_models.0.attn.logit_scale", "_orig_mod.backbone.bi_inter_models.0.attn.q_bias", "_orig_mod.backbone.bi_inter_models.0.attn.v_bias", "_orig_mod.backbone.bi_inter_models.0.attn.relative_coords_table", "_orig_mod.backbone.bi_inter_models.0.attn.relative_position_index", "_orig_mod.backbone.bi_inter_models.0.attn.cpb_mlp.0.weight", "_orig_mod.backbone.bi_inter_models.0.attn.cpb_mlp.0.bias", "_orig_mod.backbone.bi_inter_models.0.attn.cpb_mlp.2.weight", "_orig_mod.backbone.bi_inter_models.0.attn.qkv.weight", "_orig_mod.backbone.bi_inter_models.0.attn.proj.weight", "_orig_mod.backbone.bi_inter_models.0.attn.proj.bias", "_orig_mod.backbone.bi_inter_models.0.norm2.weight", "_orig_mod.backbone.bi_inter_models.0.norm2.bias", "_orig_mod.backbone.bi_inter_models.0.mlp.fc1.weight", "_orig_mod.backbone.bi_inter_models.0.mlp.fc1.bias", "_orig_mod.backbone.bi_inter_models.0.mlp.fc2.weight", "_orig_mod.backbone.bi_inter_models.0.mlp.fc2.bias", "_orig_mod.backbone.bi_inter_models.1.norm1.weight", "_orig_mod.backbone.bi_inter_models.1.norm1.bias", "_orig_mod.backbone.bi_inter_models.1.attn.logit_scale", "_orig_mod.backbone.bi_inter_models.1.attn.q_bias", "_orig_mod.backbone.bi_inter_models.1.attn.v_bias", "_orig_mod.backbone.bi_inter_models.1.attn.relative_coords_table", "_orig_mod.backbone.bi_inter_models.1.attn.relative_position_index", "_orig_mod.backbone.bi_inter_models.1.attn.cpb_mlp.0.weight", "_orig_mod.backbone.bi_inter_models.1.attn.cpb_mlp.0.bias", "_orig_mod.backbone.bi_inter_models.1.attn.cpb_mlp.2.weight", "_orig_mod.backbone.bi_inter_models.1.attn.qkv.weight", "_orig_mod.backbone.bi_inter_models.1.attn.proj.weight", "_orig_mod.backbone.bi_inter_models.1.attn.proj.bias", "_orig_mod.backbone.bi_inter_models.1.norm2.weight", "_orig_mod.backbone.bi_inter_models.1.norm2.bias", "_orig_mod.backbone.bi_inter_models.1.mlp.fc1.weight", "_orig_mod.backbone.bi_inter_models.1.mlp.fc1.bias", "_orig_mod.backbone.bi_inter_models.1.mlp.fc2.weight", "_orig_mod.backbone.bi_inter_models.1.mlp.fc2.bias", "_orig_mod.backbone.bi_inter_models.2.norm1.weight", "_orig_mod.backbone.bi_inter_models.2.norm1.bias", "_orig_mod.backbone.bi_inter_models.2.attn.logit_scale", "_orig_mod.backbone.bi_inter_models.2.attn.q_bias", "_orig_mod.backbone.bi_inter_models.2.attn.v_bias", "_orig_mod.backbone.bi_inter_models.2.attn.relative_coords_table", "_orig_mod.backbone.bi_inter_models.2.attn.relative_position_index", "_orig_mod.backbone.bi_inter_models.2.attn.cpb_mlp.0.weight", "_orig_mod.backbone.bi_inter_models.2.attn.cpb_mlp.0.bias", "_orig_mod.backbone.bi_inter_models.2.attn.cpb_mlp.2.weight", "_orig_mod.backbone.bi_inter_models.2.attn.qkv.weight", "_orig_mod.backbone.bi_inter_models.2.attn.proj.weight", "_orig_mod.backbone.bi_inter_models.2.attn.proj.bias", "_orig_mod.backbone.bi_inter_models.2.norm2.weight", "_orig_mod.backbone.bi_inter_models.2.norm2.bias", "_orig_mod.backbone.bi_inter_models.2.mlp.fc1.weight", "_orig_mod.backbone.bi_inter_models.2.mlp.fc1.bias", "_orig_mod.backbone.bi_inter_models.2.mlp.fc2.weight", "_orig_mod.backbone.bi_inter_models.2.mlp.fc2.bias", "_orig_mod.mid_convs.0.0.weight", "_orig_mod.mid_convs.0.0.bias", "_orig_mod.mid_convs.1.0.weight", "_orig_mod.mid_convs.1.0.bias", "_orig_mod.mid_convs.2.0.weight", "_orig_mod.mid_convs.2.0.bias", "_orig_mod.mid_convs.3.0.weight", "_orig_mod.mid_convs.3.0.bias", "_orig_mod.edger.conv.weight", "_orig_mod.edger.conv.bias", "_orig_mod.ifa_fuse.pes.0.row_embed.weight", "_orig_mod.ifa_fuse.pes.0.col_embed.weight", "_orig_mod.ifa_fuse.pes.1.row_embed.weight", "_orig_mod.ifa_fuse.pes.1.col_embed.weight", "_orig_mod.ifa_fuse.pes.2.row_embed.weight", "_orig_mod.ifa_fuse.pes.2.col_embed.weight", "_orig_mod.ifa_fuse.pes.3.row_embed.weight", "_orig_mod.ifa_fuse.pes.3.col_embed.weight", "_orig_mod.ifa_fuse.imnet.0.weight", "_orig_mod.ifa_fuse.imnet.0.bias", "_orig_mod.ifa_fuse.imnet.1.weight", "_orig_mod.ifa_fuse.imnet.1.bias", "_orig_mod.ifa_fuse.imnet.1.running_mean", "_orig_mod.ifa_fuse.imnet.1.running_var", "_orig_mod.classifier.0.weight", "_orig_mod.classifier.1.weight", "_orig_mod.classifier.1.bias", "_orig_mod.classifier.1.running_mean", "_orig_mod.classifier.1.running_var", "_orig_mod.classifier.3.weight", "_orig_mod.classifier.3.bias". 
	Unexpected key(s) in state_dict: "backbone.backbone.conv1.weight", "backbone.backbone.bn1.weight", "backbone.backbone.bn1.bias", "backbone.backbone.bn1.running_mean", "backbone.backbone.bn1.running_var", "backbone.backbone.bn1.num_batches_tracked", "backbone.backbone.layer1.0.conv1.weight", "backbone.backbone.layer1.0.bn1.weight", "backbone.backbone.layer1.0.bn1.bias", "backbone.backbone.layer1.0.bn1.running_mean", "backbone.backbone.layer1.0.bn1.running_var", "backbone.backbone.layer1.0.bn1.num_batches_tracked", "backbone.backbone.layer1.0.conv2.weight", "backbone.backbone.layer1.0.bn2.weight", "backbone.backbone.layer1.0.bn2.bias", "backbone.backbone.layer1.0.bn2.running_mean", "backbone.backbone.layer1.0.bn2.running_var", "backbone.backbone.layer1.0.bn2.num_batches_tracked", "backbone.backbone.layer1.1.conv1.weight", "backbone.backbone.layer1.1.bn1.weight", "backbone.backbone.layer1.1.bn1.bias", "backbone.backbone.layer1.1.bn1.running_mean", "backbone.backbone.layer1.1.bn1.running_var", "backbone.backbone.layer1.1.bn1.num_batches_tracked", "backbone.backbone.layer1.1.conv2.weight", "backbone.backbone.layer1.1.bn2.weight", "backbone.backbone.layer1.1.bn2.bias", "backbone.backbone.layer1.1.bn2.running_mean", "backbone.backbone.layer1.1.bn2.running_var", "backbone.backbone.layer1.1.bn2.num_batches_tracked", "backbone.backbone.layer2.0.conv1.weight", "backbone.backbone.layer2.0.bn1.weight", "backbone.backbone.layer2.0.bn1.bias", "backbone.backbone.layer2.0.bn1.running_mean", "backbone.backbone.layer2.0.bn1.running_var", "backbone.backbone.layer2.0.bn1.num_batches_tracked", "backbone.backbone.layer2.0.conv2.weight", "backbone.backbone.layer2.0.bn2.weight", "backbone.backbone.layer2.0.bn2.bias", "backbone.backbone.layer2.0.bn2.running_mean", "backbone.backbone.layer2.0.bn2.running_var", "backbone.backbone.layer2.0.bn2.num_batches_tracked", "backbone.backbone.layer2.0.downsample.0.weight", "backbone.backbone.layer2.0.downsample.1.weight", "backbone.backbone.layer2.0.downsample.1.bias", "backbone.backbone.layer2.0.downsample.1.running_mean", "backbone.backbone.layer2.0.downsample.1.running_var", "backbone.backbone.layer2.0.downsample.1.num_batches_tracked", "backbone.backbone.layer2.1.conv1.weight", "backbone.backbone.layer2.1.bn1.weight", "backbone.backbone.layer2.1.bn1.bias", "backbone.backbone.layer2.1.bn1.running_mean", "backbone.backbone.layer2.1.bn1.running_var", "backbone.backbone.layer2.1.bn1.num_batches_tracked", "backbone.backbone.layer2.1.conv2.weight", "backbone.backbone.layer2.1.bn2.weight", "backbone.backbone.layer2.1.bn2.bias", "backbone.backbone.layer2.1.bn2.running_mean", "backbone.backbone.layer2.1.bn2.running_var", "backbone.backbone.layer2.1.bn2.num_batches_tracked", "backbone.backbone.layer3.0.conv1.weight", "backbone.backbone.layer3.0.bn1.weight", "backbone.backbone.layer3.0.bn1.bias", "backbone.backbone.layer3.0.bn1.running_mean", "backbone.backbone.layer3.0.bn1.running_var", "backbone.backbone.layer3.0.bn1.num_batches_tracked", "backbone.backbone.layer3.0.conv2.weight", "backbone.backbone.layer3.0.bn2.weight", "backbone.backbone.layer3.0.bn2.bias", "backbone.backbone.layer3.0.bn2.running_mean", "backbone.backbone.layer3.0.bn2.running_var", "backbone.backbone.layer3.0.bn2.num_batches_tracked", "backbone.backbone.layer3.0.downsample.0.weight", "backbone.backbone.layer3.0.downsample.1.weight", "backbone.backbone.layer3.0.downsample.1.bias", "backbone.backbone.layer3.0.downsample.1.running_mean", "backbone.backbone.layer3.0.downsample.1.running_var", "backbone.backbone.layer3.0.downsample.1.num_batches_tracked", "backbone.backbone.layer3.1.conv1.weight", "backbone.backbone.layer3.1.bn1.weight", "backbone.backbone.layer3.1.bn1.bias", "backbone.backbone.layer3.1.bn1.running_mean", "backbone.backbone.layer3.1.bn1.running_var", "backbone.backbone.layer3.1.bn1.num_batches_tracked", "backbone.backbone.layer3.1.conv2.weight", "backbone.backbone.layer3.1.bn2.weight", "backbone.backbone.layer3.1.bn2.bias", "backbone.backbone.layer3.1.bn2.running_mean", "backbone.backbone.layer3.1.bn2.running_var", "backbone.backbone.layer3.1.bn2.num_batches_tracked", "backbone.backbone.layer4.0.conv1.weight", "backbone.backbone.layer4.0.bn1.weight", "backbone.backbone.layer4.0.bn1.bias", "backbone.backbone.layer4.0.bn1.running_mean", "backbone.backbone.layer4.0.bn1.running_var", "backbone.backbone.layer4.0.bn1.num_batches_tracked", "backbone.backbone.layer4.0.conv2.weight", "backbone.backbone.layer4.0.bn2.weight", "backbone.backbone.layer4.0.bn2.bias", "backbone.backbone.layer4.0.bn2.running_mean", "backbone.backbone.layer4.0.bn2.running_var", "backbone.backbone.layer4.0.bn2.num_batches_tracked", "backbone.backbone.layer4.0.downsample.0.weight", "backbone.backbone.layer4.0.downsample.1.weight", "backbone.backbone.layer4.0.downsample.1.bias", "backbone.backbone.layer4.0.downsample.1.running_mean", "backbone.backbone.layer4.0.downsample.1.running_var", "backbone.backbone.layer4.0.downsample.1.num_batches_tracked", "backbone.backbone.layer4.1.conv1.weight", "backbone.backbone.layer4.1.bn1.weight", "backbone.backbone.layer4.1.bn1.bias", "backbone.backbone.layer4.1.bn1.running_mean", "backbone.backbone.layer4.1.bn1.running_var", "backbone.backbone.layer4.1.bn1.num_batches_tracked", "backbone.backbone.layer4.1.conv2.weight", "backbone.backbone.layer4.1.bn2.weight", "backbone.backbone.layer4.1.bn2.bias", "backbone.backbone.layer4.1.bn2.running_mean", "backbone.backbone.layer4.1.bn2.running_var", "backbone.backbone.layer4.1.bn2.num_batches_tracked", "backbone.backbone.fc.weight", "backbone.backbone.fc.bias", "backbone.bi_inter_models.0.norm1.weight", "backbone.bi_inter_models.0.norm1.bias", "backbone.bi_inter_models.0.attn.logit_scale", "backbone.bi_inter_models.0.attn.q_bias", "backbone.bi_inter_models.0.attn.v_bias", "backbone.bi_inter_models.0.attn.relative_coords_table", "backbone.bi_inter_models.0.attn.relative_position_index", "backbone.bi_inter_models.0.attn.cpb_mlp.0.weight", "backbone.bi_inter_models.0.attn.cpb_mlp.0.bias", "backbone.bi_inter_models.0.attn.cpb_mlp.2.weight", "backbone.bi_inter_models.0.attn.qkv.weight", "backbone.bi_inter_models.0.attn.proj.weight", "backbone.bi_inter_models.0.attn.proj.bias", "backbone.bi_inter_models.0.norm2.weight", "backbone.bi_inter_models.0.norm2.bias", "backbone.bi_inter_models.0.mlp.fc1.weight", "backbone.bi_inter_models.0.mlp.fc1.bias", "backbone.bi_inter_models.0.mlp.fc2.weight", "backbone.bi_inter_models.0.mlp.fc2.bias", "backbone.bi_inter_models.1.norm1.weight", "backbone.bi_inter_models.1.norm1.bias", "backbone.bi_inter_models.1.attn.logit_scale", "backbone.bi_inter_models.1.attn.q_bias", "backbone.bi_inter_models.1.attn.v_bias", "backbone.bi_inter_models.1.attn.relative_coords_table", "backbone.bi_inter_models.1.attn.relative_position_index", "backbone.bi_inter_models.1.attn.cpb_mlp.0.weight", "backbone.bi_inter_models.1.attn.cpb_mlp.0.bias", "backbone.bi_inter_models.1.attn.cpb_mlp.2.weight", "backbone.bi_inter_models.1.attn.qkv.weight", "backbone.bi_inter_models.1.attn.proj.weight", "backbone.bi_inter_models.1.attn.proj.bias", "backbone.bi_inter_models.1.norm2.weight", "backbone.bi_inter_models.1.norm2.bias", "backbone.bi_inter_models.1.mlp.fc1.weight", "backbone.bi_inter_models.1.mlp.fc1.bias", "backbone.bi_inter_models.1.mlp.fc2.weight", "backbone.bi_inter_models.1.mlp.fc2.bias", "backbone.bi_inter_models.2.norm1.weight", "backbone.bi_inter_models.2.norm1.bias", "backbone.bi_inter_models.2.attn.logit_scale", "backbone.bi_inter_models.2.attn.q_bias", "backbone.bi_inter_models.2.attn.v_bias", "backbone.bi_inter_models.2.attn.relative_coords_table", "backbone.bi_inter_models.2.attn.relative_position_index", "backbone.bi_inter_models.2.attn.cpb_mlp.0.weight", "backbone.bi_inter_models.2.attn.cpb_mlp.0.bias", "backbone.bi_inter_models.2.attn.cpb_mlp.2.weight", "backbone.bi_inter_models.2.attn.qkv.weight", "backbone.bi_inter_models.2.attn.proj.weight", "backbone.bi_inter_models.2.attn.proj.bias", "backbone.bi_inter_models.2.norm2.weight", "backbone.bi_inter_models.2.norm2.bias", "backbone.bi_inter_models.2.mlp.fc1.weight", "backbone.bi_inter_models.2.mlp.fc1.bias", "backbone.bi_inter_models.2.mlp.fc2.weight", "backbone.bi_inter_models.2.mlp.fc2.bias", "mid_convs.0.0.weight", "mid_convs.0.0.bias", "mid_convs.1.0.weight", "mid_convs.1.0.bias", "mid_convs.2.0.weight", "mid_convs.2.0.bias", "mid_convs.3.0.weight", "mid_convs.3.0.bias", "edger.conv.weight", "edger.conv.bias", "ifa_fuse.pes.0.row_embed.weight", "ifa_fuse.pes.0.col_embed.weight", "ifa_fuse.pes.1.row_embed.weight", "ifa_fuse.pes.1.col_embed.weight", "ifa_fuse.pes.2.row_embed.weight", "ifa_fuse.pes.2.col_embed.weight", "ifa_fuse.pes.3.row_embed.weight", "ifa_fuse.pes.3.col_embed.weight", "ifa_fuse.imnet.0.weight", "ifa_fuse.imnet.0.bias", "ifa_fuse.imnet.1.weight", "ifa_fuse.imnet.1.bias", "ifa_fuse.imnet.1.running_mean", "ifa_fuse.imnet.1.running_var", "ifa_fuse.imnet.1.num_batches_tracked", "classifier.0.weight", "classifier.1.weight", "classifier.1.bias", "classifier.1.running_mean", "classifier.1.running_var", "classifier.1.num_batches_tracked", "classifier.3.weight", "classifier.3.bias". 
	
Which is indicating a mismatch between the provided checkpoint and the expected one. This is true for the models.evaluator.CDEvaluator as well as models.basic_model.CDEvaluator. Others were not tested.

**Comment by justchenhao** [comment]
Thanks for your attention. Sorry for the late reply. It seems the issues come from the operation of "torch.compile" because a model compiled with torch.compile will be added a prefix '_orig_mod.' to state_dict() of the model.  To address it, we have muted the line "net=torch.compile(net)" in the `networks.py`.
